version: "2"

services:
  db:
    container_name: "psql"
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASS: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ~/dbdata:/var/lib/postgresql/data
